### ISSUE TITLE
[BUG] "Item Size" Queue propertis numerically not working.

### ISSUE THREAD

**Issue by AleksanderData** [FreeRTOS/FreeRTOS-Kernel#251]
I find one problem (maybe bug) in CMSIS working with FreeRTOS. Working on the STMCubeIDE and programing F103RB (NUCLEO). I create the Queues. Properties "Item Size" set it to "20" (number). I want to convey a structure of this size. Default propertis is "uint16_t" (character string).  
During operation, only the first 4 bytes of the structure are transferred.
I debug program and find problem and repear this.
In the file cmsis.os.c replase line 766
with
     const osMessageQDef_t os_messageQ_def_##name = \
    { (queue_sz), sizeof (type), NULL, NULL  } 
to
     const osMessageQDef_t os_messageQ_def_##name = \
     { (queue_sz), type, NULL, NULL  }
Delete "sizeof"
After the change, program work good.

**Comment by RichardBarry** [comment]
Thanks for reporting, but first I don't think this is a bug but the way CMSIS RTOS APIs work (which is different to FreeRTOS), and second the code you are reporting a bug in is not our code by the CMSIS wrapper for our code :)  I recommend you discuss on either the ST or ARM forums depending on who authored the code as I think both ST and ARM provide CMSIS wrappers for FreeRTOS.  I would also suggest posting as a support request rather than a bug in the first instance.
