### ISSUE TITLE
[BUG] portVECTACTIVE_MASK incorrect in Cortex M4F port

### ISSUE THREAD

**Issue by scotteshaw** [FreeRTOS/FreeRTOS-Kernel#45]
**Describe the bug**
The definition of portVECTACTIVE_MASK seems to be incorrect in the cortex M4 ports. Based on the ARMv7-M Architecture Reference Manual (Page B3-655) it seems like the correct mask for `portVECTACTIVE_MASK` should be 0x1FF, but is 0xFF the cortex M4 port and perhaps others.

**Target**
- Development board: [n/a]
- Instruction Set Architecture: [Cortex M4]
- IDE and version: [n/a]
- Toolchain and version: [n/a]

**Host**
- Host OS: [n/a]
- Version: [n/a]

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/63121000/78392293-036a0980-75b6-11ea-906e-63441a010d99.png)

**Comment by jefftenney** [comment]
For what it's worth, I can think of a couple of reasons to leave the definition as is.  First, bit 8 is always zero on M4 because the exception number is limited to 255 by the M4 implementation of ARMv7-M.  In fact the Cortex-M comparison table here https://developer.arm.com/ip-products/processors/cortex-m/cortex-m4 indicates none of the ARMv7-M implementations exceed exception number 255 (external interrupts limited to 240).  The second reason is that using 0xFF allows more efficient code than 0x1FF allows.  The compiler can generate a single byte load instruction (LDRB) instead of a load (LDR) followed by a bitfield extraction (UBFX).

**Comment by scotteshaw** [comment]
This makes perfect sense. Thanks!
